[package]
name = "hel-colored"
version = "0.4.0"
edition = "2021"
description = "ANSI string colorizer and styler"
license = "GPL-3.0"
repository = "https://github.com/Hellaeh/hel-colored.git"

[dev-dependencies]
colored = "2.0.0"