[package]
name = "hel-colored"
version = "0.1.0"
edition = "2021"
description = "ANSI escape string colorizer"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
