[package]
name = "hel-colored"
version = "0.2.0"
edition = "2021"
description = "ANSI escape string colorizer"
license = "MIT"
repository = "https://github.com/Hellaeh/hel-colored.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
